# Generated by Django 2.2.6 on 2019-12-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pyrex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
    ]
