# Generated by Django 2.2.6 on 2020-01-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pyrex_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyrex',
            name='foods',
            field=models.ManyToManyField(to='main_app.Food'),
        ),
    ]
